model_list:
  - model_name: gemini-2.0-flash
    litellm_params:
      model: gemini/gemini-2.0-flash
      api_key: os.environ/GOOGLE_API_KEY
      
  - model_name: gemini-2.0-flash-lite
    litellm_params:
      model: gemini/gemini-2.0-flash # Assuming lite uses the same base model ID
      api_key: os.environ/GOOGLE_API_KEY

  - model_name: gemma3-12b-it
    litellm_params:
      model: ollama/gemma3:12b-it-q8_0
      api_base: os.environ/OLLAMA_API_BASE
      
  - model_name: gemma3-27b-it-qat
    litellm_params:
      model: ollama/gemma3:27b-it-qat
      api_base: os.environ/OLLAMA_API_BASE

  - model_name: gpt-4.1
    litellm_params:
      model: openai/gpt-4.1-2025-04-14
      api_key: os.environ/OPENAI_API_KEY

  - model_name: gpt-4.1-mini
    litellm_params:
      model: openai/gpt-4.1-mini-2025-04-14
      api_key: os.environ/OPENAI_API_KEY

  - model_name: gpt-4.1-nano
    litellm_params:
      model: openai/gpt-4.1-nano-2025-04-14
      api_key: os.environ/OPENAI_API_KEY

  - model_name: gpt-4.5-preview
    litellm_params:
      model: openai/gpt-4.5-preview-2025-02-27
      api_key: os.environ/OPENAI_API_KEY

  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o-2024-08-06
      api_key: os.environ/OPENAI_API_KEY

  - model_name: gpt-4o-audio-preview
    litellm_params:
      model: openai/gpt-4o-audio-preview-2024-12-17
      api_key: os.environ/OPENAI_API_KEY

  - model_name: gpt-4o-realtime-preview
    litellm_params:
      model: openai/gpt-4o-realtime-preview-2024-12-17
      api_key: os.environ/OPENAI_API_KEY

  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini-2024-07-18
      api_key: os.environ/OPENAI_API_KEY

  - model_name: gpt-4o-mini-audio-preview
    litellm_params:
      model: openai/gpt-4o-mini-audio-preview-2024-12-17
      api_key: os.environ/OPENAI_API_KEY

  - model_name: mistral-small3.1
    litellm_params:
      model: ollama/mistral-small3.1:24b-instruct-2503-q8_0
      api_base: os.environ/OLLAMA_API_BASE

  - model_name: gemini-2.5-pro-preview-03-25
    litellm_params:
      model: gemini/gemini-2.5-pro-preview-03-25
      api_key: os.environ/GOOGLE_API_KEY

  - model_name: gemini-2.5-flash-preview-04-17
    litellm_params:
      model: gemini/gemini-2.5-flash-preview-04-17
      api_key: os.environ/GOOGLE_API_KEY

  - model_name: qwen3-30b-a3b
    litellm_params:
      model: ollama/qwen3:30b-a3b
      api_base: os.environ/OLLAMA_API_BASE

  - model_name: qwen3-30b-a3b-mlx
    litellm_params:
      model: lm_studio/qwen3-30b-a3b-mlx
      api_base: os.environ/LM_STUDIO_API_BASE
      api_key: lm-studio
  - model_name: qwen3-30b-a3b
    litellm_params:
      model: lm_studio/qwen3-30b-a3b
      api_base: os.environ/LM_STUDIO_API_BASE
      api_key: lm-studio

  # MoonshotAI Kimi K2 (free) - OpenRouter
  - model_name: kimi-k2-free
    litellm_params:
      model: openrouter/moonshotai/kimi-k2:free
      api_key: os.environ/OPENROUTER_API_KEY

  # Qwen3 Coder (free) - OpenRouter
  - model_name: qwen3-coder-free
    litellm_params:
      model: openrouter/qwen/qwen3-coder:free
      api_key: os.environ/OPENROUTER_API_KEY

  # Qwen3 235B A22B Instruct 2507 (free) - OpenRouter
  - model_name: qwen3-235b-a22b-2507-free
    litellm_params:
      model: openrouter/qwen/qwen3-235b-a22b-2507:free
      api_key: os.environ/OPENROUTER_API_KEY

  # Qwen3 235B A22B Thinking 2507 - OpenRouter
  - model_name: qwen3-235b-a22b-thinking-2507
    litellm_params:
      model: openrouter/qwen/qwen3-235b-a22b-thinking-2507
      api_key: os.environ/OPENROUTER_API_KEY

  # This catch-all allows you to use any default model not explicitly defined
  - model_name: "*"
    litellm_params:
      model: "*"

litellm_settings:
  drop_params: True
  success_callback: []  # Add callbacks if needed

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY  # Read master key from environment variable
  use_database: False