model_list:
  - model_name: gemini-2.0-flash
    litellm_params:
      model: gemini/gemini-2.0-flash
      api_key: os.environ/GOOGLE_API_KEY
      
  - model_name: gemini-2.0-flash-lite
    litellm_params:
      model: gemini/gemini-2.0-flash # Assuming lite uses the same base model ID
      api_key: os.environ/GOOGLE_API_KEY

  - model_name: gemma3-12b-it
    litellm_params:
      model: ollama/gemma3:12b-it-q8_0
      api_base: os.environ/OLLAMA_API_BASE
      
  # This catch-all allows you to use any default model not explicitly defined
  - model_name: "*" 
    litellm_params:
      model: "*"

litellm_settings:
  drop_params: True
  success_callback: []  # Add callbacks if needed

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY  # Read master key from environment variable
  use_database: False